version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - npm run client-cloudfront-invalidation

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
